// export const seatData = new Array();
// for (let i = 0; i < 24; i++) {
//   seatData.push({
//     id: i,
//     selected: false,
//     status: 1
//   });
// }

export const time = new Array();
for (let i = 1; i < 6; i++) {
  time.push(5 * i)
}

export const seatData = [
  // {
  //   "device_id": "1",
  //   "title": "舒服按摩测试1号",
  //   "macno": "2019030418000001",
  //   "img": "",
  //   "status": 1,
  //   "address": "广东省东莞市坝翔商业街下坝坊上东国际(北区)",
  //   "area_id": "0",
  //   "site_id": "1",
  //   "chair_status": "0",
  //   "waist_ache": "0",
  //   "back_ache": "0",
  //   "shoulder_ache": "0",
  //   "neck_ache": "0",
  //   "run_status": "0",
  //   "error": "0",
  //   "longitude": "",
  //   "latitude": "",
  //   "height": "",
  //   "heartbeat_time": "1552632179",
  //   "ctime": "1552629967",
  //   "health_status": "0",
  //   "order_id": "0",
  //   "subscribe_id": "0",
  //   "inside_url": "0",
  //   "device_type_id": "0",
  //   "device_type": "2",
  //   "iccid": null,
  //   "agent_id": "118",
  //   "sim": null,
  //   "option_id": "0",
  //   "lng": "120.665942",
  //   "lat": "31.893711",
  //   "pause": "0",
  //   "touch": "0",
  //   "assess": "0",
  //   "agent_divide_into": "1",
  //   "site_divide_into": "0",
  //   "is_fans": "1",
  //   "seat_number": "1",
  //   selected: false
  // },
  // {
  //   "device_id": "1640",
  //   "title": "舒服按摩测试2号",
  //   "macno": "2019030418000002",
  //   "img": "",
  //   "status": 1,
  //   "address": "广东省东莞市坝翔商业街下坝坊上东国际(北区)",
  //   "area_id": "0",
  //   "site_id": "1",
  //   "chair_status": "0",
  //   "waist_ache": "0",
  //   "back_ache": "0",
  //   "shoulder_ache": "0",
  //   "neck_ache": "0",
  //   "run_status": "0",
  //   "error": "0",
  //   "longitude": "",
  //   "latitude": "",
  //   "height": "",
  //   "heartbeat_time": "1552722533",
  //   "ctime": "1552629967",
  //   "health_status": "0",
  //   "order_id": "0",
  //   "subscribe_id": "0",
  //   "inside_url": "0",
  //   "device_type_id": "0",
  //   "device_type": "2",
  //   "iccid": null,
  //   "agent_id": "118",
  //   "sim": null,
  //   "option_id": "0",
  //   "lng": "120.665942",
  //   "lat": "31.893711",
  //   "pause": "0",
  //   "touch": "0",
  //   "assess": "0",
  //   "agent_divide_into": "1",
  //   "site_divide_into": "0",
  //   "is_fans": "1",
  //   "seat_number": "2",
  //   selected: false
  // },
  // {
  //   "device_id": "2",
  //   "title": "舒服按摩测试3号",
  //   "macno": "2019030418000003",
  //   "img": "",
  //   "status": 1,
  //   "address": "广东省东莞市坝翔商业街下坝坊上东国际(北区)",
  //   "area_id": "0",
  //   "site_id": "1",
  //   "chair_status": "0",
  //   "waist_ache": "0",
  //   "back_ache": "0",
  //   "shoulder_ache": "0",
  //   "neck_ache": "0",
  //   "run_status": "0",
  //   "error": "0",
  //   "longitude": "",
  //   "latitude": "",
  //   "height": "",
  //   "heartbeat_time": "1552632179",
  //   "ctime": "1552629967",
  //   "health_status": "0",
  //   "order_id": "0",
  //   "subscribe_id": "0",
  //   "inside_url": "0",
  //   "device_type_id": "0",
  //   "device_type": "2",
  //   "iccid": null,
  //   "agent_id": "118",
  //   "sim": null,
  //   "option_id": "0",
  //   "lng": "120.665942",
  //   "lat": "31.893711",
  //   "pause": "0",
  //   "touch": "0",
  //   "assess": "0",
  //   "agent_divide_into": "1",
  //   "site_divide_into": "0",
  //   "is_fans": "1",
  //   "seat_number": "3",
  //   selected: false
  // },
  // {
  //   "device_id": "3",
  //   "title": "舒服按摩测试4号",
  //   "macno": "2019030418000004",
  //   "img": "",
  //   "status":1,
  //   "address": "广东省东莞市坝翔商业街下坝坊上东国际(北区)",
  //   "area_id": "0",
  //   "site_id": "1",
  //   "chair_status": "0",
  //   "waist_ache": "0",
  //   "back_ache": "0",
  //   "shoulder_ache": "0",
  //   "neck_ache": "0",
  //   "run_status": "0",
  //   "error": "0",
  //   "longitude": "",
  //   "latitude": "",
  //   "height": "",
  //   "heartbeat_time": "1552632179",
  //   "ctime": "1552629967",
  //   "health_status": "0",
  //   "order_id": "0",
  //   "subscribe_id": "0",
  //   "inside_url": "0",
  //   "device_type_id": "0",
  //   "device_type": "2",
  //   "iccid": null,
  //   "agent_id": "118",
  //   "sim": null,
  //   "option_id": "0",
  //   "lng": "120.665942",
  //   "lat": "31.893711",
  //   "pause": "0",
  //   "touch": "0",
  //   "assess": "0",
  //   "agent_divide_into": "1",
  //   "site_divide_into": "0",
  //   "is_fans": "1",
  //   "seat_number": "4",
  //   selected: false
  // },
  // {
  //   "device_id": "5",
  //   "title": "舒服按摩测试5号",
  //   "macno": "2019030418000005",
  //   "img": "",
  //   "status": 1,
  //   "address": "广东省东莞市坝翔商业街下坝坊上东国际(北区)",
  //   "area_id": "0",
  //   "site_id": "1",
  //   "chair_status": "0",
  //   "waist_ache": "0",
  //   "back_ache": "0",
  //   "shoulder_ache": "0",
  //   "neck_ache": "0",
  //   "run_status": "0",
  //   "error": "0",
  //   "longitude": "",
  //   "latitude": "",
  //   "height": "",
  //   "heartbeat_time": "1552632179",
  //   "ctime": "1552629967",
  //   "health_status": "0",
  //   "order_id": "0",
  //   "subscribe_id": "0",
  //   "inside_url": "0",
  //   "device_type_id": "0",
  //   "device_type": "2",
  //   "iccid": null,
  //   "agent_id": "118",
  //   "sim": null,
  //   "option_id": "0",
  //   "lng": "120.665942",
  //   "lat": "31.893711",
  //   "pause": "0",
  //   "touch": "0",
  //   "assess": "0",
  //   "agent_divide_into": "1",
  //   "site_divide_into": "0",
  //   "is_fans": "1",
  //   "seat_number": "5",
  //   selected: false
  // }
]