import Vue from 'vue';
import {
  Popup,
  Picker,
  Swipe,
  SwipeItem,
  Lazyload,
  Cell,
  CellGroup,
  Icon,
  RadioGroup,
  Radio,
  Button,
  Dialog,
  SwipeCell,
  Field,
  Uploader,
  List,
  PullRefresh,
  Search,
  Badge,
  BadgeGroup,
  Card,
  Stepper,
  SubmitBar,
  NavBar,
  Checkbox,
  CheckboxGroup,
  AddressList,
  AddressEdit,
  SwitchCell,
  Area,
  GoodsAction,
  GoodsActionBigBtn,
  GoodsActionMiniBtn
}
from 'vant';
import 'vant/lib/index.css';
Vue
  .use(Popup)
  .use(Picker)
  .use(Swipe)
  .use(SwipeItem)
  .use(Lazyload)
  .use(Cell)
  .use(CellGroup)
  .use(Icon)
  .use(RadioGroup)
  .use(Radio)
  .use(Button)
  .use(Dialog)
  .use(SwipeCell)
  .use(Field)
  .use(Uploader)
  .use(List)
  .use(PullRefresh)
  .use(Search)
  .use(Badge)
  .use(BadgeGroup)
  .use(Card)
  .use(Stepper)
  .use(SubmitBar)
  .use(NavBar)
  .use(Checkbox)
  .use(CheckboxGroup)
  .use(AddressList)
  .use(AddressEdit)
  .use(SwitchCell)
  .use(Area)
  .use(GoodsAction)
  .use(GoodsActionBigBtn)
  .use(GoodsActionMiniBtn)